name: magika
version: 1.0.2
base: core24
title: Magika
summary: Fast and accurate AI powered file content types detection
description: |
  Magika is a novel AI-powered file type detection tool that relies on the
  recent advance of deep learning to provide accurate detection. Under the hood,
  Magika employs a custom, highly optimized model that only weighs about a few
  MBs, and enables precise file identification within milliseconds, even when
  running on a single CPU. Magika has been trained and evaluated on a dataset of
  ~100M samples across 200+ content types (covering both binary and textual file
  formats), and it achieves an average ~99% accuracy on our test set.

license: Apache-2.0
grade: stable
confinement: strict
issues:
  - https://github.com/alexmurray/magika-snap/issues
contact:
  - https://github.com/alexmurray/magika-snap/issues
source-code:
  - https://github.com/google/magika
  - https://github.com/alexmurray/magika-snap
website:
  - https://securityresearch.google/magika/

apps:
  magika:
    command: bin/magika
    plugs:
      - home
      - removable-media

parts:
  magika:
    plugin: rust
    source: https://github.com/google/magika.git
    source-tag: cli/v$CRAFT_PROJECT_VERSION
    rust-path: ["rust/cli"]
    build-packages:
      - libssl-dev

